#: import Window kivy.core.window.Window

<User_widet>:
    orientation: 'vertical'
    size_hint: None, None
    pos_hint: {'center_x':.5}
    padding: dp(8),dp(8),dp(8),dp(8)
    spacing: dp(8)
    
    BoxLayout:
        spacing: dp(16)
        size_hint_y: None
        height: dp(60)
        MDLabel:
            text: u'\uF004'
            font_name: 'fonts\\materialdesignicons-webfont.ttf'
            size_hint: None, None
            size: dp(32), dp(32)
            pos_hint: {'center_x':.5,'center_y':.5}
            color: 0,0,0,1
            font_size: '24sp'

        MDLabel:
            text: root.username
            color: 0,0,0,1
            size_hint_y: 1
            halign:'left'

    TextField:
        id: txt
        hint_text: 'Password'
        size_hint_y: None
        height: dp(38)
        hint_text_color: 0,0,0,.8
        padding: dp(8), dp(8),0,0
        password: True

    MDFlatButton:
        id: btn
        text: 'Proceed'
        size_hint_x: None
        width: dp(100)
        color:  0, 52/255, 102/255, .63
        pos_hint: {'right':1}

    
            
    
             
<BoxWhite>:
            
<MDLabel>:
    font_name: 'fonts/Roboto-Bold.ttf' if self.font_style == 'Title' else 'fonts/Roboto-Medium.ttf' if self.font_style == 'Subhead' else 'fonts/Roboto-Regular.ttf' 
    font_size: '12sp' if root.font_style == 'Caption' else '12sp'
    text_size: (self.width, None)
    markup: True
    color: 0,0,0,1

<ButtonBase>:
    font_name: 'fonts\\materialdesignicons-webfont.ttf'
    text_size: self.texture_size

<MDSeparator>
    canvas:
        Color:
            rgba: root.color
        Rectangle:
            size: self.size
            pos: self.pos
            
<IconButton>:
    size_hint: None,None
    font_size: '32sp'
   
<MaterialWidget>
    canvas.before:
        Color:
            rgba: 1,1,1,.4

        Rectangle:
            size: self.size
            pos: self.pos
            
    canvas.after:

        Color:
            rgba: 0,0,0,.3 

        Line:
            rectangle: self.x, self.y, self.width, self.height

        Color:
            rgba: 1,1,1,.3

        Line:
            rectangle: self.x, self.y, self.width, self.height

<Ripplebtn>:
    
<TitleButtons>:
    canvas:
        Color:
            rgba: 0,0,0,0
            group: 'a'

        Rectangle:
            size: self.size
            pos: self.pos

<TextFieldM>:
    TextInput:
        id: txt
        text: root.text
        hint_text: root.hint_text
        background_color: 245/255, 245/255, 245/255, 0
        background_normal: ''
        font_name:'fonts\\Montserrat-Regular.ttf'
        background_active: ''
        padding_y: 5,0
        cursor_color: 0/255, 109/255, 240/255, 1        
        hint_text_color: 0,52/255, 102/255,1
        padding: dp(16), dp(15),0,0
        multiline: False
    
<TextField>:
    canvas.after:
        Color:
            rgba: 0,0,0, .2

        Line:
            rectangle: self.x + dp(1), self.y, self.width - dp(1), self.height -  dp(1)

    background_color: 245/255, 245/255, 245/255, .2
    background_normal: ''
    background_active: ''
    cursor_color: 0/255, 109/255, 240/255, 1
    padding: dp(16), dp(15),0,0
    multiline: False
    
<Search_Tab>:
    txt: txt
    btn: btn
    FloatLayout:
        TextInput:
            id: txt
            background_normal: ''
            background_active: ''
            background_color: 1,1,1,0
            cursor_color: 0/255, 109/255, 240/255, 1
            padding: dp(16), dp(14),0,0
            pos_hint:{'x':.01, 'center_y':.5}
            multiline: False
            size_hint: .83,None
            height: root.height - 2
            hint_text: 'Search book by Accession number'
            hint_text_color: 0,0,0,.83
        IconButton:
            id: btn
            text: u'\uF349'
            color: 0,0,0,.5
            font_size: '32sp'
            size: dp(48), dp(48)
            pos_hint: {'right':.95,'center_y':.5}
            
        
<MDFlatButtonc>:
    canvas.before:
        Color:
            rgba: 0,0,0, .3

        Line:
            rectangle: self.x, self.y, self.width,self.height

        Rectangle:
            size:self.size
            pos: self.pos
            
    color: 1,1,1,1

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            filters:['*.jpg']
	    
        BoxLayout:
            size_hint_y: None
            height: 30
            MDFlatButtonc:
                size_hint_x: .5
                text: "Cancel"
                on_release: root.cancel()

            MDFlatButtonc:
                size_hint_x: .5
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<LableI>:
    canvas.before:
        Color:
            rgba: 1,1,1,.8
        Rectangle:
            size: self.size
            pos: self.pos
    color: 0,0,0,1
        
    
<DashLabel>:
    lbl: lbl
    orientation:'vertical'
    MDLabel:
        id: lbl
        size_hint: 1,.9
        font_style:'Headline'
        halign:'center'
        font_size: 80
        text:'0'
        
    MDLabel:
        size_hint: 1,None
        size: 1,30
        halign:'center'
        text:'Total number of books'
            
<AnalysisRV>:
    canvas.before:
        Color:
            rgba: 1,1,1,.8
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 0,0,0,.2
        Line:
            points: self.x, self.y, self.x, self.top, self.right, self.top, self.right, self.y, self.x, self.y
            
    color:0,0,0,1
    shorten:True
    shorten_from:'center'
    halign:'center'
    
    on_press: root.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.show_book_quantity(self.text)   

<RecycleV>:
    viewclass: 'AnalysisRV'
    RecycleBoxLayout:
        default_size: None, dp(30)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        padding: 2,2,2,2
        spacing: 2
        
<AnalysisRVBarcode>:
    canvas.before:
        Color:
            rgba: 1,1,1,.8
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 0,0,0,.2
        Line:
            points: self.x, self.y, self.x, self.top, self.right, self.top, self.right, self.y, self.x, self.y
            
    color:0,0,0,1
    shorten:True
    shorten_from:'center'
    markup: True
    halign:'center'
    background_normal:''
    background_down:''

<RecycleVBarcode>:
    viewclass: 'AnalysisRVBarcode'
    bar_width: 15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.4]
    
    RecycleBoxLayout:
        default_size: None, dp(30)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        padding: 15, 15, 15, 15
        
<Scroller>:
    
<Backup_restore>:
    mdl: mdl
    btn: btn
    imgb: imgb
    spacing:0
    padding: 20,0,0,0
    Image:
        id: imgb
        source: 'pics/restore.png'
        mipmap:True
        size_hint:.05,.6
        allow_stretch:True
        keep_ratio: False
        pos_hint:{'center_x':.5,'center_y':.5}

    MDLabel:
        id: mdl
        text:''
        halign:'center'
        size_hint:.4,.5
        pos_hint:{'center_x':.5,'center_y':.5}

    MDSeparator:
        size_hint: None,.5
        size: 1,1
        pos_hint:{'center_x':.5,'center_y':.5}

    MDFlatButtonc:
        id: btn
        text:'Restore'
        size_hint: .3,1
        pos_hint:{'center_x':.5,'center_y':.5}


<NotificationB>:
    adm_id_lbl: adm_id_lbl
    adm_id: adm_id
    name: name
    titl: titl
    reg_as: reg_as
    show_mem: show_mem
    date_pass: date_pass
    
    BoxLayout:
        size_hint: .3,1
        padding:20,0,0,0
        
        Image:
            id: imgb
            source: 'pics/total_not.png'
            mipmap:True
            size_hint: .0,.7
            allow_stretch:True
            keep_ratio: False
            pos_hint: {'center_x':.5,'center_y':.5}
            color: 0, 52/255, 102/255, 1
            opacity:.8
                
    MDSeparator:
        pos_hint:{'center_x':.5,'center_y':.5}
        size_hint:None,.5
        size: 1, self.parent.height-20
        
    GridLayout:
        size_hint: .7,1
        cols: 2
        padding: 0,15,0,0
        
        MDLabel:
            id: adm_id_lbl
            text:'Adm_no :'
            size_hint: 1,None
            size: 1,20
            color: 0,0,0,.8
            halign:'right'
        MDLabel:
            id: adm_id
            halign:'left'
            size_hint: 1,None
            size: 1,20
            color: 0,0,0,.8
        MDLabel:
            text:'Name : '
            size_hint: 1,None
            size: 1,20
            halign:'right'
        MDLabel:
            id: name
            halign:'left'
            size_hint: 1,None
            size: 1,20
            
        MDLabel:
            text: 'Book title : '
            size_hint: 1,None
            size: 1,20
            halign:'right'
            
        MDLabel:
            id: titl
            halign:'left'
            size_hint: 1,None
            size: 1,20
            shorten: True
            shorten_from: 'right'
            
        MDLabel:
            text:'Date passed by : '
            size_hint: 1,None
            size: 1,20
            halign:'right'
        MDLabel:
            id: date_pass
            halign:'left'
            size_hint: 1,None
            size: 1,20
            
        MDLabel:
            text:'Registered as : '
            size_hint: 1,None
            size: 1,20
            color: 0,0,0,.8
            halign:'right'
        MDLabel:
            id: reg_as
            halign:'left'
            size_hint: 1,None
            size: 1,20
            color: 0,0,0,.8
            
    FloatLayout:
        size_hint:.0,.0
        MDFlatButtonc:
            id: show_mem
            x: root.x
            y: root.y
            size_hint: None,None
            size: root.width, root.height
        
<ScreenMN>:
    not_total: not_total
    not_std: not_std
    not_teach: not_teach
    not_non: not_non
    
    BoxLayout:
        canvas:
            Color:
                rgba: 30/255,30/255,30/255,1
            Rectangle:
                size: self.size
                pos: self.pos
                
        orientation: 'vertical'
        BoxLayout:
            orientation:'vertical'
            padding: self.parent.width/2-75, 0, 0, 50
            size_hint: 1,.8
            Image:
                source: 'pics\\total_not.png'
                allow_stretch: True
                keep_ratio: False
                size_hint: None, 1
                size: 150,1
        BoxLayout:
            size_hint: 1,.1
            MDLabel:
                id: not_total
                text: '0 Notifications'
                halign: 'center'
                size_hint: 1,1
                color: 1,1,1, .83
                
    BoxLayout:
        canvas:
            Color:
                rgba: 255/255,215/255,0/255,1
            Rectangle:
                size: self.size
                pos: self.pos
                
        orientation: 'vertical'
        BoxLayout:
            orientation:'vertical'
            padding: self.parent.width/2-self.width/2, 0, 0, 50
            size_hint: 1,.8
            Image:
                source: 'pics/students.png'
                allow_stretch: True
                keep_ratio: False
                size_hint: .5, 1
                pos_hint:{'center_x':.5,'center_y':.5}
                
                size: 150,1
        BoxLayout:
            size_hint: 1,.1
            MDLabel:
                id: not_std
                text: '0 should return books'
                halign: 'center'
                size_hint: 1,1

    BoxLayout:
        canvas:
            Color:
                rgba: 0/255,128/255,0/255,1
            Rectangle:
                size: self.size
                pos: self.pos
        orientation: 'vertical'
        BoxLayout:
            orientation:'vertical'
            padding: self.parent.width/2-self.width/2, 0, 0, 50
            size_hint: 1,.8
            Image:
                source: 'pics/teachers.png'
                allow_stretch: True
                keep_ratio: False
                size_hint: .5, 1
                pos_hint:{'center_x':.5,'center_y':.5}
                
                size: 150,1
                
        BoxLayout:
            size_hint: 1,.1
            MDLabel:
                id: not_teach
                text: '0 should return books'
                halign: 'center'
                size_hint: 1,1
                
    BoxLayout:
        canvas:
            Color:
                rgba: 104/255,131/255,139/255,1
            Rectangle:
                size: self.size
                pos: self.pos
        orientation: 'vertical'
        BoxLayout:
            orientation:'vertical'
            padding: self.parent.width/2-self.width/2, 0, 0, 50
            size_hint: 1,.8
            Image:
                source: 'pics/non.png'
                allow_stretch: True
                keep_ratio: False
                size_hint: .8, 1
                pos_hint:{'center_x':.5,'center_y':.5}
                size: 150,1
        BoxLayout:
            size_hint: 1,.1
            MDLabel:
                id: not_non
                text: '0 should return books'
                halign: 'center'
                size_hint: 1,1
                    
<HistoryButton>:
    gdl: gdl
    acc_n: acc_n
    titl: titl
    publ: publ
    imgb: imgb
    showmore: showmore
    
    padding: 0,10,0,0
    orientation:'vertical'
    BoxLayout:
        padding:20,0,0,0
        FloatLayout:
            size_hint:None,1
            size: 100,1
            Image:
                id: imgb
                source:'pics/book_history.png'
                mipmap:True
                size_hint:None,None
                size: 60,60
                allow_stretch:True
                keep_ratio: False
                x: self.parent.x+20
                y: self.parent.y+self.parent.height-self.height

        GridLayout:
            id: gdl
            cols:2
            
            MDLabel:
                text:'Book accession no. :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.8
            MDLabel:
                id: acc_n
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.8
            MDLabel:
                text:'Book title :'
                size_hint:1,None
                size:1,20
                
                
            MDLabel:
                id: titl
                size_hint:1,None
                size:1,20
                halign:'left'
                shorten: True
                shorten_from: 'right'
                
            MDLabel:
                text:'Book publisher :'
                size_hint:1,None
                size:1,20
                shorten: True
                shorten_from: 'right'
                
            MDLabel:
                id: publ
                size_hint:1,None
                size:1,20
                halign:'left'
                
    MDSeparator:
        size_hint:1,None
        size:1,1
    BoxLayout:
        size_hint:1,None
        size:1,20
        padding: 0,0,1,1
        
        MDFlatButtonc:
            id: showmore
            size_hint:1,1
            text:'More...'
            on_release: root.show_more_less()
            

<BorrowButton>:
    gdl: gdl
    acc_n: acc_n
    titl: titl
    publ: publ
    imgb: imgb
    marklost: marklost
    ret_book: ret_book
    date_iss: date_iss
    date_supp: date_supp
    date_pass: date_pass
    memb_reg: memb_reg
    adm_id: adm_id
    pers: pers
    memb_serv: memb_serv
    
    padding: 0,10,0,0
    orientation:'vertical'
    BoxLayout:
        padding:20,0,0,0
        FloatLayout:
            size_hint:None,1
            size: 100,1
            Image:
                id: imgb
                source:'pics/book.png'
                mipmap:True
                size_hint:None,None
                size: 80,80
                allow_stretch:True
                keep_ratio: False
                x: self.parent.x+20
                y: self.parent.y+self.parent.height-self.height-20

        GridLayout:
            id: gdl
            cols:2
            
            MDLabel:
                id: pers
                text:'Admission no. :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.8
            MDLabel:
                id: adm_id
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.8
            MDLabel:
                text:'Book accession no. :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.7
            MDLabel:
                id: acc_n
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.7
            MDLabel:
                text:'Book title :'
                size_hint: 1,None
                size: 1,20
                
            MDLabel:
                id: titl
                size_hint:1,None
                size:1,20
                halign:'left'
                shorten:True
                shorten_from:'right'
                
            MDLabel:
                text:'Book publisher :'
                size_hint:1,None
                size:1,20
            MDLabel:
                id: publ
                size_hint:1,None
                size:1,20
                halign:'left'
                shorten:True
                shorten_from:'right'
                
            MDLabel:
                text:'Date issued :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.8
            MDLabel:
                id: date_iss
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.8
            MDLabel:
                text:'Date suppossed to returned :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.8
            MDLabel:
                id: date_supp
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.8
            MDLabel:
                text:'Date passed by :'
                size_hint:1,None
                size:1,20
            MDLabel:
                id: date_pass
                size_hint:1,None
                size:1,20
                halign:'left'
            MDLabel:
                text:'Member registered as :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.7
            MDLabel:
                id: memb_reg
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.7
            MDLabel:
                text:'Member served by :'
                size_hint:1,None
                size:1,20
                color: 0,0,0,.7
            MDLabel:
                id: memb_serv
                size_hint:1,None
                size:1,20
                halign:'left'
                color: 0,0,0,.7
            
    MDSeparator:
        size_hint:1,None
        size:1,1
    BoxLayout:
        size_hint:1,None
        size:1,20
        padding: 0,0,1,1
        MDFlatButtonc:
            id: marklost
            size_hint:1,1
            text:'Mark book as lost'
            on_release: root.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.mark_book_as_lost(acc_n.text, adm_id.text, marklost, imgb, memb_reg.text)
        MDSeparator:
            size_hint: None,1
            size: 1,1
        MDFlatButtonc:
            id: markdamaged
            size_hint:1,1
            text:'Mark book as damaged'
            on_release: root.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.mark_book_as_damaged(acc_n.text, adm_id.text, markdamaged, imgb, memb_reg.text)
        MDSeparator:
            size_hint: None,1
            size: 1,1
        
        MDFlatButtonc:
            id: ret_book
            size_hint:1,1
            text:'Return book'
            on_release: root.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.return_book(acc_n.text, titl.text, publ.text, date_iss.text, date_supp.text, date_pass.text, memb_reg.text, adm_id.text,marklost)

<ResButton>:

<header_left>:
	size_hint:None,None
	size:20,25				
	background_color:0, 52/255, 102/255, 1
	background_normal:''

<Lists_widget>:
    canvas.after:
        Color:
            rgba: 0, 52/255, 102/255, 1
        Line:
            points: self.x, self.y, self.x, self.top, self.right, self.top, self.right, self.y, self.x, self.y

    canvas.before:
        Color:
            rgba: 1,1,1,.3

        Rectangle:
            size: self.size
            pos: self.pos
            
    color:0,0,0,1
    shorten: True
    text_size:(200, None)
    shorten_from:'right'
    halign:'center'
    
<Online_b>:	
    img: img
    isbn: isbn
    titl: titl
    auth: auth
    publ: publ
    yp: yp
	
    FloatLayout:
        Image:
            id: img
            source:'pics/thumb.jpg'
            size_hint:None,None
            size: 160,self.parent.height-4
            allow_stretch:True
            keep_ratio:False
            x:self.parent.x+10
            y:self.parent.y+2
            nocache: True
    
        MDLabel:
            id: titl
            text:'The Famous Five'
            font_style:'Title'
            color:0,0,0,1
            size_hint:None,None
            size: self.parent.width-180,40
            x:img.x+img.width+10
            y: self.parent.y+self.parent.height-self.height-5
            shorten:True
            shorten_from:'right'
            font_size:'15'
                    
        MDLabel:
            id: isbn
            text:'Isbn:  98094358035'
            font_style:'Caption'
            color:0,0,0,.5
            size_hint:None,None
            size: self.parent.width-220,40
            x:img.x+img.width+50
            y: titl.y-30
            font_size:'12'
            shorten:True
            shorten_from:'right'
                    
        MDLabel:
            id: auth
            text:'author: Hasan goerge'
            font_style:'Caption'
            color:0,0,0,.5
            size_hint:None,None
            size: self.parent.width-220,40
            x:img.x+img.width+50
            y: isbn.y-20
            font_size:'12'
            shorten:True
            shorten_from:'right'
                    
        MDLabel:
            id: publ
            text:'publisher '
            font_style:'Caption'
            color:0,0,0,.5
            size_hint:None,None
            size: self.parent.width-220,40
            x:img.x+img.width+50
            y: auth.y-20
            font_size:'12'
            shorten:True
            shorten_from:'right'
                    
        MDLabel:
            id: yp
            text:'Year of publication: 2014'
            font_style:'Caption'
            color:0,0,0,.5
            size_hint:None,None
            size: self.parent.width-220,40
            x:img.x+img.width+50
            y: publ.y-20
            font_size:'12'
            shorten:True
            shorten_from:'right'
            
                    
        MDFlatButtonc:
            text:'Fill'
            x:self.parent.x+self.parent.width-self.width-20
            y:self.parent.y+10
            on_release:root.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.fill_form_with_online(titl.text, isbn.text, auth.text, publ.text, yp.text)
            
            
<TableWidget>:
    h_scroll: h_scroll.__self__
    recv_add: recv_add.__self__
    diablos: diablos
    header: header
    
    BoxLayout:
        orientation: "vertical"
                
        Scroller0:
            id: h_scroll
            size_hint: 1,None
            height:26
            
            GridLayout:
                id: header
            	size_hint: None, None
            	width: self.minimum_width
    	        height: 26
    	    	spacing:1,0
                cols: 17

                Button:
                    text:'Book accession no.'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Id .'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Ibsn'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Title'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1
                    
                Button:
                    text:'Publisher'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1
                    
                Button:
                    text:'Edition'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1
                    
                Button:
                    text:'Author'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Place of publication'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1
                    
                Button:
                    text:'Year of publication'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Category'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1
                    
                Button:
                    text:'Shelve no.'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Lost'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Lost by'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Borrowed'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Borrowed by'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Damaged'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

                Button:
                    text:'Damaged by'
                    size_hint:None,None
                    height:25
                    width:200
                    background_normal:''
                    background_color: 0, 52/255, 102/255, 1
                    color:1,1,1,1

    
        BoxLayout		
            Recv:
                id: recv_add
                viewclass: 'SelectableLabel'
                bar_color: 0, 52/255, 102/255, 1
                bar_inactive_color:[0,0,0,0.3]
        		
                SelectableRecycleGridLayout:
                    id: diablos
                    cols: 17
                    default_size: 200, dp(26)
                    default_size_hint: None, None
                    size_hint: None,None
                    spacing:0,0
                    padding: 1,0,0,10
                    height: self.minimum_height
                    width:self.minimum_width
                    orientation: 'vertical'
                    multiselect: True
                    touch_multiselect: False
                    

<CardCommon>:
    
<Imageframe>:
    img: img
    FloatLayout:
        AsyncImage:
            id: img
            source:'pics/account.png'
            allow_stretch:True
            mipmap:True
            keep_ratio:False
            size_hint:None,None
            size:self.parent.width-1,self.parent.height-40
            x:self.parent.x+0.5
            y:self.parent.y+20

<CardChange>:

<Base_iconb>:
    text: root.icon
    
<CardHolder>:
    float1: float1
    lbltitle: lbltitle
    sep: sep
    boxl: boxl
    orientation:'vertical'
    
    FloatLayout:
        id: float1
        canvas:
            Color:
                rgba: 1,1,1,.6

            Rectangle:
                source:'pics\\metal.jpg'
                size: self.size
                pos: self.pos
                
            
            
    
        MDLabel:
            id: lbltitle
            text:'TITLE'
            font_name: 'fonts\\Montserrat-SemiBold.ttf'
            font_size:'18'
            halign:'center'
            valing:'middle'
            size_hint:None,None
            size: self.parent.width, 50
            x: self.parent.x
            y: self.parent.y+self.parent.height-self.height
            color: 0,52/255,102/255, 1
            
        MDSeparator:
            id: sep
            size_hint:None,None
            size: self.parent.width,0
            x: self.parent.x
            y: lbltitle.y
            
    BoxLayout:
        id: boxl
        size_hint:None,None
        size: self.parent.width,self.parent.height-50
        orientation:'vertical'

<ScrollWidget>:
    grid: grid.__self__
    
    size_hint:1,1
    	  
    ScrollView:
        size_hint: 1,1
        
        bar_width: 15
        scroll_type:['bars']
        bar_color: 0, 52/255, 102/255, 1
        bar_inactive_color:[0,0,0,0.4]
        
        GridLayout:
            id: grid
            cols:1
            size_hint:None,None
            size: self.parent.width,self.minimum_height
            pos:self.parent.pos
            padding:1,0,15,0

######## Database Navigator
            
<Label>:
    halign:'center'
    markup:False
    size_hint:None,None
    font_size:'13'
    size: 200,50
    color:0,0,0,1
    
<LableI>:
    canvas:
        Color:
            rgba: 0,0,0,.2
        Line:
            points: self.x, self.y, self.x, self.top, self.right, self.top, self.right, self.y, self.x, self.y
    valign:'middle'
    halign:'center'
    font_style:'Caption'
    size_hint:(1,None)
    height:0
    
    
<Input>:
    font_size:'13'

<Navigator>:


<Scrollwidget_Books>:
    acc_n: acc_n
    isbn: isbn
    tit: tit
    pubr: pubr
    edition: edition
    auth: auth
    pob: pob
    yop: yop
    categ: categ
    shelve: shelve
    size_hint:1,1
    
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    orientation: 'vertical'
    
    GridLayout:
        size_hint:1,None
        size: 1,self.minimum_height
        padding: 0,0,20,0
        spacing: 8
        
        cols:2

        FloatLayout:
            
            size_hint:None,None
            size: 0,66
            padding:10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width, 66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8, 20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Accession number :'

                    Input:
                        id: acc_n
                        text:''
                        input_filter:'int'
                    
        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Isbn :'
        Input:
            id: isbn
            text:''
            
        MDLabel:
            text:'Title :'
        Input:
            id: tit
            text:''
            
        MDLabel:
            text:'Publisher :'
        Input:
            id: pubr
            text:''
            
        MDLabel:
            text:'Edition :'
        Input:
            id: edition
            text:''
            
        MDLabel:
            text:'Author :'
        Input:
            id: auth
            text:''
            
        MDLabel:
            text:'Place of publication :'
        Input:
            id: pob
            text:''
            
        MDLabel:
            text:'Year of publication :'
        Input:
            id: yop
            text:''
            
        MDLabel:
            text:'Category :'
        Input:
            id: categ
            text:''
            
        MDLabel:
            text:'Shelve no. :'
        Input:
            id: shelve
            text:''

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1
        
<Scrollwidget_Books_many>:
    acc_n: acc_n
    isbn: isbn
    tit: tit
    pubr: pubr
    edition: edition
    auth: auth
    pob: pob
    yop: yop
    categ: categ
    shelve: shelve
    book_q: book_q
    
    size_hint:1,1
    
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    
    
    GridLayout:
        size_hint:1,None
        size: 1,self.minimum_height
        padding: 0,0,20,0
        spacing: 8
        
        cols:2

        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding:10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width,66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Accession number :'

                    Input:
                        id: acc_n
                        text:''
                        input_filter:'int'

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Isbn :'
        Input:
            id: isbn
            text:''
            
        MDLabel:
            text:'Title :'
        Input:
            id: tit
            text:''
            
        MDLabel:
            text:'Publisher :'
        Input:
            id: pubr
            text:''
            
        MDLabel:
            text:'Edition :'
        Input:
            id: edition
            text:''
            
        MDLabel:
            text:'Author :'
        Input:
            id: auth
            text:''
            
        MDLabel:
            text:'Place of publication :'
        Input:
            id: pob
            text:''
            
        MDLabel:
            text:'Year of publication :'
        Input:
            id: yop
            text:''
            
        MDLabel:
            text:'Category :'
        Input:
            id: categ
            text:''
            
        MDLabel:
            text:'Shelve no. :'
        Input:
            id: shelve
            text:''

        MDLabel:
            text:'Book quantity :'
        Input:
            id: book_q
            text:''
            input_filter:'int'

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1
                

<Scrollwidget_std_reg>:
    adm_no: adm_no
    id_no: id_no
    name: name
    clas: clas
    gender_female: gender_female
    gender_male: gender_male
    
    size_hint:1,1    
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    
    
    GridLayout:
        size_hint:1,None
        size: 1, self.minimum_height
        padding: 0,0,20,0
        spacing:8
        cols:2

        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding:10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width,66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Admission no. :'

                    Input:
                        id: adm_no
                        text:''

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Id no. :'
        Input:
            id: id_no
            text:''
            
        MDLabel:
            text:'Name :'
        Input:
            id: name
            text:''

        MDLabel:
            text:'Class :'
        Input:
            id: clas
            text:''

        MDLabel:
            text:'Male :'
        CheckBox:
            id: gender_male
            size_hint: None, None
            size: dp(48), dp(48)
            active: True
            group:'gender'
            on_press: self.active=True

        MDLabel:
            text:'Female :'
        CheckBox:
            id: gender_female
            size_hint: None, None
            size: dp(48), dp(48)
            group:'gender'
            on_press: self.active=True

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1
        

<Scrollwidget_non_and_teacher_reg>:
    id_no: id_no
    name: name
    gender_female: gender_female
    gender_male: gender_male
    
    size_hint:1,1    
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    
    GridLayout:
        size_hint:1,None
        size: 1,self.minimum_height
        padding: 0,0,20,0
        spacing: 8
        cols:2

        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding:10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width, 66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Id no. :'

                    Input:
                        id: id_no
                        text:''

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Name :'
        Input:
            id: name
            text:''

        MDLabel:
            text:'Male :'
        CheckBox:
            id: gender_male
            size_hint: None, None
            size: dp(48), dp(48)
            active: True
            group:'genders'
            on_press: self.active=True

        MDLabel:
            text:'Female :'
        CheckBox:
            id: gender_female
            size_hint: None, None
            size: dp(48), dp(48)
            group:'genders'
            on_press: self.active=True

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1

<Scrollwidget_std_issue_return>:
    adm_no: adm_no
    id_no: id_no
    name: name
    clas: clas
    book_acc_no: book_acc_no
    titl: titl
    dat_issue: dat_issue
    date_ret: date_ret
    pub: pub
    
    size_hint:1,1
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    
    
    GridLayout:
        size_hint:1,None
        size: 1,self.minimum_height
        padding: 0,0,20,0
        spacing:8
        cols:2
        
        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding: 10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width,66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Admission no. :'

                    Input:
                        id: adm_no
                        text:''

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Name :'
        Input:
            id: name
            text:''
            readonly:True

        MDLabel:
            text:'Id no. :'
        Input:
            id: id_no
            text:''
            readonly:True

        MDLabel:
            text:'Class :'
        Input:
            id: clas
            text:''
            readonly:True

        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding: 10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width,66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding: 0,8,20,8
                    
                    MDLabel:
                        id:lbl_unknown
                        text:'Book Accession no. :'

                    Input:
                        id: book_acc_no
                        text:''

        FloatLayout:
            size_hint: None,None
            size:0,0
            
        MDLabel:
            text:'Book Title :'
        Input:
            id: titl
            text:''
            readonly:True

        MDLabel:
            text:'Book publisher :'
        Input:
            id: pub
            text:''
            readonly:True
            
        MDLabel:
            text:'Date issued :'
        DatePicker:
            id: dat_issue
            font_size:'13'

        MDLabel:
            text:'Date Supposed to return :'
        DatePicker:
            id: date_ret
            font_size:'13'

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1
                
            
<Scrollwidget_non_teacher_issue_return>:
    id_no: id_no
    name: name
    book_acc_no: book_acc_no
    titl: titl
    dat_issue: dat_issue
    date_ret: date_ret
    pub: pub
    
    
    size_hint:1,1
    bar_width:15
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,0.2]
    
    
    GridLayout:
        size_hint:1,None
        size: 1,self.minimum_height
        padding: 0,0,20,0
        spacing: 8
        cols:2

        FloatLayout:
            size_hint: None,None
            size: 0,66
            padding: 10,0,0,0
            CardCommon:
                size_hint: None,None
                size: self.parent.parent.width, 66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        text:'Id no. :'

                    Input:
                        id: id_no
                        text:''

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Name :'
        Input:
            id: name
            text:''
            readonly:True

        FloatLayout:
            size_hint:None,None
            size: 0,66
            padding: 10,0,0,0
            CardCommon:
                size_hint: None,None
                size: root.width,66
                pos_hint: {'x':1,'center_y':.5}
              
                BoxLayout:
                    padding:0,8,20,8
                    
                    MDLabel:
                        text:'Book Accession no. :'

                    Input:
                        id: book_acc_no
                        text:''

        FloatLayout:
            size_hint:None,None
            size:0,0
            
        MDLabel:
            text:'Book Title :'
        Input:
            id: titl
            text:''
            readonly:True

        MDLabel:
            text:'Book publisher :'
        Input:
            id: pub
            text:''
            readonly:True
            
        MDLabel:
            text:'Date issue :'

        DatePicker:
            id: dat_issue
            font_size:'13'

        MDLabel:
            text:'Date Supposed to return :'

        DatePicker:
            id: date_ret
            font_size:'13'

        FloatLayout:
            size_hint: None, None
            size: 1, 1
            MDSeparator:
                size_hint: None, None
                size: root.width, 1

<MDiconB>:
    canvas.before:
        Color:
            group: 'a'
            rgba: 0,52/255, 102/255, 1

        Ellipse:
            size: self.size
            pos: self.pos

        Color:
            group: 'a'
            rgba: 1,1,1,1

        Color:
            rgba: 1,1,1,1
            
        SmoothLine:
            ellipse: self.x, self.y, self.width, self.height
            
    font_name:'fonts\\materialdesignicons-webfont.ttf'
    text: root.icon
    font_size: '19sp'
    color: 1,1,1, 1
    size_hint: None, None
    size: dp(32), dp(32)

<AutocompleteButton>:
    size_hint: 1, None
    height: dp(30)
    shorten_from: 'right'
    shorten: True
    color: 0,0,0,.83

<CustomTgglButton>:
    background_normal: ''
    background_color: 1,1,1,.2
    size_hint_x: .8
    font_name: 'fonts\\Montserrat-Regular.ttf'

<CustomDropdown>:
    canvas.before:
        Color:
            rgba: 1,1,1,.8

        Rectangle:
            size: self.size
            pos: self.pos
            
    canvas.after:

        Color:
            rgba: 0,0,0,.2

        Line:
            rectangle: self.x, self.y, self.width, self.height
            
    bar_width: 10
    scroll_type:['bars']
    bar_color: 0, 52/255, 102/255, 1
    bar_inactive_color:[0,0,0,.2]
 
<Toolbar>:
    clear_f: clear_f
    update: update
    first_r: first_r
    prev_r: prev_r
    add_r: add_r
    del_r: del_r
    next_r: next_r
    last_r: last_r
    
    size_hint: 1,None
    size: 1,50

    BoxLayout:
        size_hint: 1,1
        FloatLayout:
            size_hint: None, 1
            width: root.width 
            
            MDiconB:
                id: clear_f
                icon:u'\uF265'
                pos_hint: { 'center_y':.5}
                x: update.x - self.width -dp(10)
            MDiconB:
                id: update
                icon:u'\uF450'
                pos_hint: { 'center_y':.5}
                x: first_r.x - self.width -dp(10)
            MDiconB:
                id: first_r
                icon:u'\uF4AB'
                pos_hint: { 'center_y':.5}
                x: prev_r.x - self.width -dp(10)
            MDiconB:
                id: prev_r
                icon:u'\uF4AE'
                pos_hint: { 'center_y':.5}
                x: add_r.x - self.width -dp(10)
            MDiconB:
                id: add_r
                icon:u'\uF1BA'
                pos_hint: {'center_x':.5, 'center_y':.5}
            MDiconB:
                id: del_r
                icon:u'\uF1C0'
                pos_hint: { 'center_y':.5}
                x: add_r.x + self.width +dp(10)
            MDiconB:
                id: next_r
                icon:u'\uF4AD'
                pos_hint: { 'center_y':.5}
                x: del_r.x + self.width +dp(10)
            MDiconB:
                id: last_r
                icon:u'\uF4AC'
                pos_hint: { 'center_y':.5}
                x: next_r.x + self.width +dp(10)

<Deletedialog>:
    size_hint: None,None
    size: dp(272), dp(181)
    orientation:'vertical'
    padding: dp(16),dp(16),dp(16),dp(16)
    spacing: dp(8)

    BoxLayout:
        size_hint_y: None
        height: dp(32)
        
        MDLabel:
            id: range
            text: 'Specify Range to delete:'
            font_style:'Subhead'
            halign:'left'
            valign:'center'

        IconButton:
            id: btnclose
            text: u'\uF156'
            color: .2,0,0,.5
            halign:'right'
            font_size: '24sp'
            size: dp(32), dp(32)
            pos_hint: {'center_x':.5,'center_y':.5}
        
            

    TextField:
        id: lblfrom
        hint_text:'From'
        text:'1'
        input_filter: 'int'
        size_hint:1,None
        size:100,dp(35)
        padding: dp(16),dp(8),dp(32),0

    TextField:
        id: lblto
        hint_text:'To'
        input_filter: 'int'
        size_hint:1,None
        size:100,dp(35)
        padding: dp(16),dp(8),dp(32),0

    BoxLayout:
        size_hint_y: None
        height: dp(32)
        spacing: dp(8)

        MDFlatButtonc:
            id: delete_Range
            text: 'Range Delete'
            color: 1,1,1,1
            size_hint: None, None
            size: dp(120), dp(32)
            halign:'center'
            pos_hint: {'center_x':.5}

        MDFlatButtonc:
            id: deleteall
            text: 'Delete Single'
            color: 1,1,1,1
            size_hint: None, None
            size: dp(120), dp(32)
            halign:'center'
            pos_hint: {'center_x':.5}

        
<Updatedialog>:
    size_hint: None,None
    size: dp(272), dp(181)
    orientation:'vertical'
    padding: dp(16),dp(16),dp(16),dp(16)
    spacing: dp(8)

    BoxLayout:
        size_hint_y: None
        height: dp(32)
        
        MDLabel:
            id: range
            text: 'Specify Range to update:'
            font_style:'Subhead'
            halign:'left'
            valign:'center'

        IconButton:
            id: btnclose
            text: u'\uF156'
            color: .2,0,0,.5
            halign:'right'
            font_size: '24sp'
            size: dp(32), dp(32)
            pos_hint: {'center_x':.5,'center_y':.5}
        
            

    TextField:
        id: lblfrom
        hint_text:'From'
        text:'1'
        input_filter: 'int'
        size_hint:1,None
        size:100,dp(35)
        padding: dp(16),dp(8),dp(32),0

    TextField:
        id: lblto
        hint_text:'To'
        input_filter: 'int'
        size_hint:1,None
        size:100,dp(35)
        padding: dp(16),dp(8),dp(32),0

    BoxLayout:
        size_hint_y: None
        height: dp(32)
        spacing: dp(8)

        MDFlatButtonc:
            id: update_Range
            text: 'Update range'
            color: 1,1,1,1
            size_hint: None, None
            size: dp(120), dp(32)
            halign:'center'
            pos_hint: {'center_x':.5}

        MDFlatButtonc:
            id: updateall
            text: 'Update all instead'
            color: 1,1,1,1
            size_hint: None, None
            size: dp(120), dp(32)
            halign:'center'
            pos_hint: {'center_x':.5}
        
    

<Images_anim>:
    size_hint:None,None
    size:50,50
    keep_ratio:False
    allow_tretch:True
    

############# End of database entry

<NotifyButton>:
    lbl_not: lbl_not
    img_s: img_s
    canvas:
        Color:
            rgba: 1,1,1,.1
        Rectangle:
            size: self.size
            pos: self.pos
            
    FloatLayout:
        Image:
            id: img_s
            source:'pics/noti.png'
            keep_ratio:False
            allow_stretch: True
            size_hint: None,None
            size: 30,self.parent.height-20
            x: self.parent.x+10
            y: self.parent.y+10
            
        MDLabel:
            id: lbl_notify
            text:'[b]Notification : [/b]'
            text_style:'Display4'
            text_size:'10'
            halign:'left'
            size_hint: None,None
            size: 100,self.parent.height
            x: self.parent.x+50
            y: self.parent.y
            markup: True
        MDLabel:
            id: lbl_not
            text:'no current notifications'
            text_style:'Caption'
            text_size:'5'
            halign:'center'
            size_hint: None,None
            size: self.parent.width,self.parent.height
            x: self.parent.x
            y: self.parent.y
            markup: True

<CointainerHeaders>:
    canvas:
        Color:
            rgba: 0, 52/255, 102/255, 1

        Rectangle:
            size: dp(5), dp(0)
            pos: 0, Window.size[1]
            group: 'rec'
    size_hint: 1, None
    size: 260, 50
    orientation: 'vertical'
    BoxLayout:
        padding: dp(16),0,dp(16),0
        spacing: dp(8)
        Label:
            text: root.icon
            font_name: 'fonts\\materialdesignicons-webfont.ttf'
            size_hint: None, None
            size: dp(32), dp(32)
            font_size: '24sp'
            color: root.color
            pos_hint: {'center_x':.5, 'center_y':.5}

        ScreenManager:
            id: sm_main
            Screen:
                name: 'one'

            Screen:
                name: 'two'
                BoxLayout:
                    padding: dp(0),0,dp(16),0
                    spacing: dp(8)
                    
                    MDLabel:
                        text: root.text
                        color: root.color
                        halign: 'left'
                        size_hint_x: None
                        width: self.parent.width - dp(32)
                        valign: 'center'
                        
                    Label:
                        text: root.icon1
                        font_size: '24sp'
                        color: root.color
                        size: dp(32), dp(32)
                        font_name: 'fonts\\materialdesignicons-webfont.ttf'
                        size_hint: None, None
                        pos_hint: {'center_x':.5, 'center_y':.5}

<Bg_p2d>:
    canvas:
        Color:
            rgba:root.bg_color

        Rectangle:
            size: self.size
            pos: self.pos
            

<Image_Theme>:
    canvas:
        Color:
            rgba: 0,0,0,.3

        SmoothLine:
            rectangle:self.x, self.y, self.width,self.height
    mipmap: True
    allow_stretch: True
    keep_ratio: False

<HoverTool>:
    size_hint_x: None
    width:dp(60)

<ScreenM>:
    stack_dash: stack_dash
    sm_content: sm_content
    stack_book_reg: stack_book_reg
    stack_student_reg: stack_student_reg
    stack_teachers_reg: stack_teachers_reg
    stack_non_teaching_reg: stack_non_teaching_reg
    stack_analysis: stack_analysis
    stack_non_teaching_borro_ret: stack_non_teaching_borro_ret
    stack_Teachers_borro_ret: stack_Teachers_borro_ret
    stack_Students_borro_ret: stack_Students_borro_ret
    stack_book_reg_table: stack_book_reg_table
    box_notify: box_notify
    noti_grid_std: noti_grid_std
    noti_grid_teach: noti_grid_teach
    noti_grid_non: noti_grid_non
    sm_noti: sm_noti
    backup_grd: backup_grd
    rvanlysis: rvanlysis
    lbl_title0: lbl_title0
    graph_plot0: graph_plot0
    lbl_analysis0: lbl_analysis0
    lbl_title1: lbl_title1
    graph_plot1: graph_plot1
    lbl_analysis1: lbl_analysis1
    books_search: books_search
    mdicon_table: mdicon_table
    img_preview: img_preview
    lbl_preview: lbl_preview
    margin_x: margin_x
    margin_y: margin_y
    nocpp: nocpp
    norpp: norpp
    sbbx: sbbx
    sbby: sbby
    chkbx_lost: chkbx_lost
    chkbx_damaged: chkbx_damaged
    chkbx_return: chkbx_return
    img_preview_reports: img_preview_reports
    rv_ret: rv_ret
    apply_b_i: apply_b_i
    
    canvas:
        Color:
            group: 'h'
            rgba: 1,1,1,1

        Rectangle:
            group: 'h'
            size: self.size
            pos: self.pos
            
    Screen:
        name:'Registration'
        
        BoxLayout:
            orientation:'vertical'
            FloatLayout:
                Image:
                    id: img_reg
                    source:'pics/pack.png'
                    keep_ratio:False
                    allow_strecth:True
                    size_hint:None,None
                    size: 100,100
                    x: self.parent.width/2-self.width/2
                    y: self.parent.height/2-self.height/2
            
                BoxLayout:
                    id: box_reg
                    size_hint:None,None
                    size: 300,60
                    spacing: 20
                    x: self.parent.width/2-self.width/2-50
                    y: img_reg.y-self.height
                    
                    TextField:
                        id: txt_one
                        size_hint:None,None
                        size:100,dp(30)
                        padding: 8,8,0,0
                        password: True
                    TextField:
                        id: txt_two
                        size_hint:None,None
                        size:100,dp(30)
                        padding: 8,8,0,0
                        password: True
                    TextField:
                        id: txt_three
                        size_hint:None,None
                        size:100,dp(30)
                        padding: 8,8,0,0
                        password: True
                    TextField:
                        id: txt_four
                        size_hint:None,None
                        size:100,dp(30)
                        padding: 8,8,0,0
                        password: True

                MDFlatButton:
                    text:'Register!'
                    x: self.parent.width/2-self.width/2
                    y: box_reg.y-self.height - dp(16)
                    on_release: root.register_app(txt_one.text, txt_two.text, txt_three.text, txt_four.text)
                    
    Screen:
        name:'login'

        FloatLayout:

            CardCommon:
                size_hint: None, 1
                pos_hint:{'center_x':.5}
                width: dp(464)
                orientation:'vertical'
                padding: 0,dp(32),0,dp(32)
                spacing: dp(32)

                Image:
                    source: 'pic_control\\icon.png'
                    mipmap: True
                    allow_stretch: True
                    keep_ratio: False
                    size_hint: None,None
                    size: dp(64), dp(64)
                    pos_hint:{'center_x':.5}

                MDLabel:
                    text: 'Log In'
                    size_hint:1, None
                    font_style: 'Subhead'
                    height: dp(32)
                    halign:'center'
                    color: 0,0,0,1

                ScrollView:
                    bar_width: dp(10)
                    pos_hint: {'center_x':.5}
                    scroll_type: ['bars']
                    BoxLayout:
                        id: box_users
                        orientation:'vertical'
                        padding: 0,dp(16),0,dp(16)
                        spacing: dp(16)
                        size_hint_y: None
                        height: self.minimum_height

                MDFlatButtonc:
                    text: 'Show more users?'
                    color: 1,1,1,1
                    size_hint: None, None
                    size: dp(400), dp(32)
                    halign:'center'
                    pos_hint: {'center_x':.5}
                    on_press: root.reload_users()

          
    Screen:
        name:'main'
        
        BoxLayout:
            HoverTool:
                canvas:
                    Color:
                        rgba: 1,1,1,.3 

                    Rectangle:
                        size:self.size
                        pos: self.pos

                    Color:
                        rgba: 0,0,0,.3 if root.line_nav==True else 1,1,1,0

                    Line:
                        rectangle: self.x,self.y, self.width,self.height
                        
                id: hvrt
                        
                orientation:'vertical'
                on_state: root.change_state_toolbar(self.state)

                BoxLayout:
                    id: headers
                    elevation: '4'
##                            canvas:
##                                Color:
##                                    rgba: 0, 52/255, 102/255, 1
##
##                                Rectangle:
##                                    size: self.size
##                                    pos: self.pos
##                                    source: root.header_wall
##
##
##                                Color:
##                                    rgba: 16/255, 78/255,139/255, .5
##
##                                Rectangle:
##                                    size: self.size
##                                    pos: self.pos

                            

                            
                    size_hint:1,None
                    size: 1,140
                   
                    FloatLayout:
                        Widget:
                            canvas:
                                Color:
                                    rgba: 1,1,1,1
                                    
                                Rectangle:
                                    source: 'pic_control\\icon.png'
                                    size: self.size
                                    pos: self.pos
                                
                                    
                            id: prof_pic
                            size_hint: None,None
                            size: 44 if hvrt.state== 'normal' else 100, 44 if hvrt.state == 'normal' else 100
                            x: self.parent.x+self.parent.width/2-self.width/2
                            y: self.parent.y+self.parent.height/2-self.height/2
                           
                            
                            
##                        IconButton:
##                            text:  u'\uF100' if root.prof_pic =='' else ''
##                            size_hint: None,None
##                            font_size: '32sp'
##                            size: 32,32
##                            color: 0,0,0,.33
##                            x: self.parent.x+self.parent.width/2-self.width/2
##                            y: self.parent.y+self.parent.height/2-self.height/2
##                            on_release: root.show_load()

##                
##                        MDSeparator:
##                            size_hint: 1,None
##                            size: 260,.5
                  #  canvas:
                   #     Color:
                    #        rgba: 0,0,0,.6
                     #   Rectangle:
                      #      size: self.size
                       #     pos: self.pos
                    
                ScrollView:
                    bar_width: 10
                    scroll_type:['bars']
                    bar_color: 0, 52/255, 102/255, 1
                    bar_inactive_color:[0,0,0,.2]
                    
                    BoxLayout:
                        id: hvrt_boxl 
                        
                        size_hint_y: None
                        height: self.minimum_height
                        orientation: 'vertical'
                        padding: 0,dp(8),0,dp(8)

                        CointainerHeaders:
                            id: contH1
                            icon: u'\uF56E'
                            group:'a'
                            text: 'Home'

                            
                            TitleButtons:
                                size_hint: 1, None
                                height: 50
                                text: "Dashboard"
                                on_press:sm_content.current='dashboard'
                                on_press: self.state='down'
                                on_press:sm_title.current='dashboard'


                        CointainerHeaders:
                            id: contH2
                            group:'a'
                            icon: u'\uF0BA'
                            text: 'Book Registration'
                            
                            TitleButtons:
                                id: ttl_one
                                size_hint: 1, None
                                height: 50
                                text: "Single"
                                on_press: root.change_to_one_reg()
                                on_press:sm_title.current='BooksReg'
                                on_press:sm_content.current='BooksReg'
                                on_press: self.state='down'
                                
                            TitleButtons:
                                id: ttl_mass
                                size_hint_x: 1
                                text: "Mass"
                                on_press: root.change_to_many_reg()
                                on_press:sm_title.current='BooksReg'
                                on_press:sm_content.current='BooksReg'
                                on_press: self.state='down'


                        CointainerHeaders:
                            id: contH3
                            icon: u'\uF332'
                            group:'a'
                            text: 'Books options'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Table view"
                                on_press:sm_content.current='BooksRegTable'
                                on_press:sm_title.current='BooksRegTable'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Generate barcode "
                                on_press:sm_title.current='barcode'
                                on_press:sm_content.current='barcode'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint: 1, None
                                height: 50
                                text: "Text to Database"
                                on_press:sm_content.current='P2D'
                                on_press: self.state='down'
                                on_press:sm_title.current='P2D'


                        CointainerHeaders:
                            id: contH4
                            icon: u'\uF004'
                            group:'a'
                            text: 'Member Registration'
                                
                            TitleButtons:
                                size_hint_x: 1
                                text: "Student"
                                on_press:sm_content.current='Students_reg'
                                on_press:sm_title.current='Students_reg'
                                on_press: self.state='down'
                            TitleButtons:
                                size_hint_x: 1
                                text: "Teacher"
                                on_press:sm_content.current='Teachers_reg'
                                on_press:sm_title.current='Teachers_reg'
                                on_press: self.state='down'
                            TitleButtons:
                                size_hint_x: 1
                                text: "Non teaching stuff"
                                on_press:sm_content.current='non_teaching_reg'
                                on_press:sm_title.current='non_teaching_reg'
                                on_press: self.state='down'


                        CointainerHeaders:
                            id: contH5
                            icon: u'\uF331'
                            group:'a'
                            text: 'Books Circulation'
                                
                            TitleButtons:
                                size_hint_x: 1
                                text: "Student"
                                on_press:sm_content.current='Students_borro_ret'
                                on_press:sm_title.current='Students_borro_ret'
                                on_press: self.state='down'
                                
                            TitleButtons:
                                size_hint_x: 1
                                text: "Teacher"
                                on_press:sm_content.current='Teachers_borro_ret'
                                on_press:sm_title.current='Teachers_borro_ret'
                                on_press: self.state='down'
                                
                            TitleButtons:
                                size_hint_x: 1
                                text: "Non teaching stuff"
                                on_press:sm_content.current='non_teaching_borro_ret'
                                on_press:sm_title.current='non_teaching_borro_ret'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Barcode scanner"
                                on_press:sm_content.current='barcode_ret'
                                on_press:sm_title.current='barcode_ret'
                                on_press: self.state='down'


                        CointainerHeaders:
                            id: contH6
                            icon: u'\uF09A'
                            group:'a'
                            text: 'Notifications'


                            TitleButtons:
                                size_hint_x: 1
                                text: "Student"
                                on_press:sm_content.current='notifications'
                                on_press:sm_title.current='notifications'
                                on_press:sm_noti.current='student'
                                on_press: self.state='down'
                                
                            TitleButtons:
                                size_hint_x: 1
                                text: "Teacher"
                                on_press:sm_content.current='notifications'
                                on_press:sm_title.current='notifications'
                                on_press:sm_noti.current='teacher'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Non teaching stuff"
                                on_press:sm_content.current='notifications'
                                on_press:sm_title.current='notifications'
                                on_press:sm_noti.current='non'
                                on_press: self.state='down'


                        CointainerHeaders:
                            id: contH7
                            icon: u'\uF37B'
                            group:'a'
                            text: 'More Options'

                    
                            TitleButtons:
                                size_hint_x: 1
                                text: "Find analysis"
                                on_press:sm_content.current='analysis'
                                on_press:sm_title.current='analysis'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Print reports"
                                on_press:sm_content.current='reports'
                                on_press:sm_title.current='reports'
                                on_press: self.state='down'
                            
                            TitleButtons:
                                size_hint_x: 1
                                text: "Backup"
                                on_press:sm_content.current='backup'
                                on_press:sm_title.current='backup'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Settings"
                                on_press:sm_content.current='settings'
                                on_press:sm_title.current='settings'
                                on_press: self.state='down'

                            TitleButtons:
                                size_hint_x: 1
                                text: "Log out"
                                on_press: root.do_want_log_out()
                    
                    
            BoxLayout:
                orientation:'vertical'
                size_hint:1,1
                
                BoxLayout:
                    size_hint:1,None
                    size:1,50
                    canvas:
                        Color:
                            rgba: 1,1,1,.3

                        Rectangle:
                            size: self.size
                            pos: self.pos
                        
                        
                    ScreenManager:
                        id: sm_title
                                  
                        Screen:
                            name:'dashboard'
                            
                            Label:
                                text:'Dashboard'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1

                        Screen:
                            name:'P2D'
                            
                            Label:
                                text:'Text to Database'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                                

                        Screen:
                            name:'BooksRegTable'
                            FloatLayout:
                                size_hint:1,None
                                size: 1,50

                                IconButton:
                                    id: mdicon_table
                                    text:  u'\uF35D'
                                    font_size: '24sp'
                                    halign: 'center'
                                    valign: 'center'
                                    color: 0,0,0,.83
                                    size: dp(64), dp(64)
                                    x: attch_btn.x + attch_btn.width - self.width
                                    pos_hint: {'center_y':.5}
                                    

                                Button:
                                    id: attch_btn
                                    x: self.parent.x+10
                                    background_normal: ''
                                    background_color: 1,1,1,.3
                                    pos_hint: {'center_y':.5}
                                    size_hint:.58,None
                                    size: self.parent.width, self.parent.height - 8
                                    on_release: mdicon_table.state='normal'
                                    on_press: mdicon_table.state='down'

                                BoxLayout:
                                    canvas:
                                        Color:
                                            rgba: 0,0,0,.3

                                        SmoothLine:
                                            rounded_rectangle: self.x, self.y, self.width,self.height, dp(4)
                                            
                                    id: mdl_selc
                                    x: self.parent.x+10
                                    pos_hint: {'center_y':.5}
                                    size_hint:.58,None
                                    size: self.parent.width-20, self.parent.height - 8

                                    TextInput:
                                        id: books_search
                                        hint_text:'Search books by title'
                                        background_normal: ''
                                        background_color: 1,1,1,0
                                        font_name:'fonts\\Montserrat-Regular.ttf'
                                        background_active: ''
                                        padding: 10,8,20,0
                                        pos_hint: {'center_y':.5}
                                        size_hint_y: None
                                        height: self.parent.height-dp(8)
                                        cursor_color: 0,52/255, 102/255,1 
                                        hint_text_color: 0,52/255, 102/255,1
                                        multiline: False
                                        on_text_validate: root.search(self.hint_text)
                                        
                                    FloatLayout:
                                        id: mdicon_table
                                        size_hint: None, None
                                        size: dp(64), dp(64)
                                        pos_hint: {'center_y':.5}
                                                                            

                                IconButton:
                                    id: mdicon_table1
                                    text: u'\uF4EB'
                                    font_size: '24sp'
                                    halign: 'center'
                                    valign: 'center'
                                    color: 0,0,0,.83
                                    x: mdl_selc.x+mdl_selc.width
                                    y: books_search.y - dp(15)
                                    size: dp(64), dp(64)
                                    on_release: root.load_recs_to_books_table()
                                    
                                MDLabel:
                                    id: mdl_selc1
                                    text:'Load Table'
                                    font_size:'10'
                                    x: mdicon_table1.x+mdicon_table1.width
                                    y:5
                                    size_hint:None,None
                                    size: 100,40
                                    color: 0,0,0,.83
                                                            
                        Screen:
                            name:'BooksReg'

                            FloatLayout:
                                size_hint:1,None
                                size: 1,dp(50)
				
                                TextFieldM:
                                    id: online_t
                                    hint_text:'Search book by isbn or title'
                                    size_hint: None,None
                                    padding: dp(8), dp(0),dp(16),dp(8)
                                    size: self.parent.width-dp(320), self.parent.height - 8
                                    pos_hint: {'center_y':.5}
                                    x:15
                                    				
                                IconButton:
                                    canvas.before:
                                        Color:
                                            rgba: 1,1,1,.43

                                        Ellipse:
                                            size: self.size
                                            pos: self.pos
                                            
                                    id: online_s
                                    text: u'\uF349'
                                    color: 0,0,0,.83
                                    x: online_t.x+ online_t.width + dp(8)
                                    pos_hint: {'center_y':.5}
                                    size_hint:None,None
                                    size: 32,32
                                    font_size: '24sp'
                                    background_color:0,0,0,0
                                    background_normal:''
                                    background_down:''
                                    on_release: root.load_internet_controls(online_t.text)

                                MDSeparator:
                                    orientation: 'vertical'
                                    size_hint_y: None
                                    height: self.parent.height/2
                                    x:online_s.x+ online_s.width + dp(16)
                                    pos_hint: {'center_y':.5}
                                    

                                MDLabel:
                                    id: autoc
                                    text:'Auto Complete:'
                                    size_hint: None, None
                                    size: dp(100), dp(50)
                                    color: 0,0,0,.83
                                    pos_hint: {'center_y':.5}
                                    x: online_s.x+ online_s.width + dp(32)

                                Switch:
                                    active: True
                                    size_hint: None, None
                                    size: dp(50), dp(50)
                                    active: False
                                    pos_hint: {'center_y':.5}
                                    x: autoc.x+ autoc.width + dp(32)
                                    on_active: root.autocomplete = True if self.active ==True else False
                                		
                                        
                        Screen:
                            name:'Students_reg'

                            Label:
                                text:'Students Registration'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                                
                                
                        Screen:
                            name:'Teachers_reg'
                            Label:
                                text:'Teachers Registration'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                                
                                
                                
                        Screen:
                            name:'non_teaching_reg'
                            Label:
                                text:'Non teaching stuff Registration'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                                
                        Screen:
                            name:'Students_borro_ret'
                            Label:
                                text:'Students circulation'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                            FloatLayout:
                                IconButton:
                                    id: refresh_notifications
                                    text: u'\uF35C'
                                    size: 48,48
                                    font_size: '24sp'
                                    color: 0,0,0,.83
                                    x: self.parent.width-self.width-20
                                    y: self.parent.y+1
                                    on_release: stack_Students_borro_ret.anim_to_state('open')
      
                        Screen:
                            name:'Teachers_borro_ret'
                            Label:
                                text:'Teachers circulation'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                            FloatLayout:
                                IconButton:
                                    id: refresh_notifications
                                    text: u'\uF35C'
                                    size: 48,48
                                    font_size: '24sp'
                                    color: 0,0,0,.83
                                    x: self.parent.width-self.width-20
                                    y: self.parent.y+1
                                    on_release: stack_Teachers_borro_ret.anim_to_state('open')
      
                                
                        Screen:
                            name:'non_teaching_borro_ret'
                            Label:
                                text:'Non Teaching stuff circulation'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1

                            FloatLayout:
                                IconButton:
                                    id: refresh_notifications
                                    text: u'\uF35C'
                                    size: 48,48
                                    font_size: '24sp'
                                    color: 0,0,0,.83
                                    x: self.parent.width-self.width-20
                                    y: self.parent.y+1
                                    on_release: stack_non_teaching_borro_ret.anim_to_state('open')
      

                        Screen:
                            name:'notifications'
                            Label:
                                text:'Notifications'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                            FloatLayout:
                                IconButton:
                                    id: refresh_notifications
                                    text:  u'\uF450'
                                    size: 48,48
                                    font_size: '24sp'
                                    color: 0,0,0,.83
                                    x: self.parent.width-self.width-20
                                    y: self.parent.y+1
                                    on_release: root.show_noti_widgets()
                                    
                        Screen:
                            name:'backup'
                            Label:
                                text:'Backup center'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                                
                            FloatLayout:
                                IconButton:
                                    id: mdicon_manuall
                                    size: 48,48
                                    font_size: '24sp'
                                    text: u'\uF06F'
                                    x: mdicon_refresh_backup.x-mdicon_refresh_backup.width
                                    y: self.parent.y+1
                                    color: 0,0,0,.83
                                    on_release: root.backup_manaully()
                                    
                                IconButton:
                                    id: mdicon_refresh_backup
                                    text:  u'\uF450'
                                    size: 48,48
                                    font_size: '24sp'
                                    x: self.parent.width-self.width-20
                                    y: self.parent.y+1
                                    color: 0,0,0,.83
                                    on_release: root.add_backup_buttons()

                        Screen:
                            name:'barcode'
                            Label:
                                text:'Generate & print barcodes'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1

                        Screen:
                            name:'analysis'
                            Label:
                                text:'Analysis'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1
                        Screen:
                            name:'settings'
                            Label:
                                text:'Settings'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1

                        Screen:
                            name:'reports'
                            Label:
                                text:'Reports and Printing'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1

                        Screen:
                            name:'barcode_ret'
                            Label:
                                text:'Return books with barcode scanner'
                                font_size: '18sp'
                                font_name: 'fonts\\Montserrat-Black.ttf'
                                font_style:'Subhead'
                                halign:'left'
                                text_size: (self.width, None)
                                padding_x:40
                                color: 0,0,0,.63
                                size_hint_x:1


                BoxLayout:
                    id: box_notify
                    size_hint:1,None
                    size: 1,0
                    
       
                BoxLayout:
                    ScreenManager:
                        id: sm_content

                        Screen:
                            name:'P2D'

                            BoxLayout:
                                id: stack_dash
                                orientation: 'vertical'
                                padding: 20,20,20,20

                                BoxLayout:
                                    orientation: 'vertical'
                                    size_hint_y: None
                                    height: dp(130)
                                    padding: 0,0,0,dp(8)
                                    
                                    MDLabel:
                                        text: 'Enter record separated by a separator(each separator distincts a field)'
                                        size_hint: 1, None
                                        halign: 'left'
                                        height: dp(30)
                                        color: 0,0,0,.63

                                    BoxLayout:
                                        size_hint_y: None
                                        height: dp(50)
                                        spacing:dp(8)
                                        TextField:
                                            id: t2r_line_txt
                                            hint_text: ''
                                            font_name: 'fonts\\Montserrat-Bold.ttf'
                                            padding: 8,10,16,0
                                            size_hint_y: None
                                            height: 40
                                            on_text_validate: root.ShowPreview()

                                        MDFlatButton:
                                            text: 'PREVIEW'
                                            size_hint_x: None
                                            width: dp(100)
                                            color:  0, 52/255, 102/255, 1
                                            on_release: root.ShowPreview()

                                        MDFlatButton:
                                            text: 'ADD RECORD'
                                            size_hint_x: None
                                            width: dp(100)
                                            color:  0, 52/255, 102/255, 1
                                            on_release: root.add_appended_rec()
                                            
                                    MDLabel:
                                        text: 'Specify the separator'
                                        size_hint_y: None
                                        height: dp(30)
                                        halign: 'left'
                                        color: 0,0,0,.63

                                    BoxLayout:
                                        size_hint_y: None
                                        height: 40
                                        spacing:dp(8)
                                        
                                        TextField:
                                            id: t2r_sep_txt
                                            text: ','
                                            padding: 8,10,16,0
                                            hint_text: "Default separator is a ','"
                                            size_hint: None, None
                                            size: dp(300), 40

                                        MDLabel:
                                            text: 'Appended records: %s'%len(root.rst_records)
                                            color: 0,0,0,.63
                                            halign: 'right'

                                        MDFlatButton:
                                            text: 'RESET'
                                            size_hint_x: None
                                            width: dp(100)
                                            color:  0, 52/255, 102/255, 1
                                            on_release: root.reset_appended_rec()
                                ScrollView:
                                    bar_width: 10
                                    scroll_type: ['bars']
                                    bar_color: 0, 52/255, 102/255, 1
                                    TextInput:
                                        id: rst_doc
                                        background_color: 245/255, 245/255, 245/255, 0
                                        background_normal: ''
                                        background_active: ''
                                        cursor_color: 0/255, 109/255, 240/255, 1
                                        font_name: 'fonts\\cour.ttf'
                                        size_hint: None, None
                                        size: dp(10)*118, max(self.minimum_height, dp(30))
                        Screen:
                            name:'dashboard'

                            StackLayout:
                                id: stack_dash
                                orientation:'lr-tb'
                                padding: 20,20,20,40
                                spacing:20
                                
                                FloatLayout:
                                    size_hint: 1, .5
                                        
                                    MaterialWidget:
                                        pos_hint: {'center_x':.5, 'center_y':.5}
                                        ScreenMN:
                                            id: smn_dash
                                            loop: True
                                            size_hint: 1,1

                                    IconButton:
                                        text: u'\uF141'
                                        pos_hint: {'center_y':.5}
                                        x: self.parent.x + dp(16)
                                        size: dp(30), dp(60)
                                        font_size: '24sp'
                                        color: 0,0,0,.63
                                        on_release: smn_dash.load_previous()

                                    IconButton:
                                        text: u'\uF142'
                                        pos_hint: {'center_y':.5}
                                        x: self.parent.x + self.parent.width - self.width - dp(16)
                                        size: dp(30), dp(60)
                                        color: 0,0,0,.63
                                        font_size: '24sp'
                                        on_release: smn_dash.load_next()

                                BoxLayout:
                                    size_hint: 1, .5
                                    orientation: 'vertical'
                                    BoxLayout:
                                        size_hint_y: None
                                        height: dp(30)
                                        Label:
                                            id: dashlabel
                                            text: 'No. of books in db'
                                            size_hint_x: None
                                            font_name: 'fonts\\Montserrat-Regular.ttf'
                                            halign: 'right'
                                            width: dp(120)
                                            color: 0,0,0,.83
                                        Label:
                                            id: dashlabel
                                            text: '0'
                                            font_name: 'fonts\\Montserrat-Regular.ttf'
                                            halign: 'right'
                                            font_style: 'Subhead'
                                            font_size: '12sp'
                                            color: 0,0,0,.83
                                    BoxLayout:
                                        

                        Screen:
                            name:'BooksRegTable'
                            BoxLayout:
                                id: stack_book_reg_table
                                padding: 10,10,10,0

                        Screen:
                            name:'BooksReg'
                            BoxLayout:
                                id: stack_book_reg
                                padding:20,20,20,20
                                spacing:20

                        Screen:
                            name:'Students_reg'
                            StackLayout:
                                id: stack_student_reg
                                orientation:'lr-tb'
                                padding:20,20,20,20
                                spacing:20
                        Screen:
                            name:'Teachers_reg'
                            StackLayout:
                                id: stack_teachers_reg
                                orientation:'tb-lr'
                                padding:20,20,20,20
                                spacing:20

                        Screen:
                            name:'non_teaching_reg'
                            StackLayout:
                                id: stack_non_teaching_reg
                                orientation:'tb-lr'
                                padding:20,20,20,20
                                spacing:20

                        
                        Screen:
                            name:'Students_borro_ret'
                            
                            NavigationDrawer:
                                id: stack_Students_borro_ret
                                touch_accept_width: dp(20)
                                anim_type: 'reveal_from_below'
                                side_panel_opacity :0

                                
                        Screen:
                            name:'Teachers_borro_ret'
                            
                            NavigationDrawer:
                                id: stack_Teachers_borro_ret
                                touch_accept_width: dp(20)
                                anim_type: 'reveal_from_below'
                                side_panel_opacity :0
                                
                                    

                        Screen:
                            name:'non_teaching_borro_ret'
                            NavigationDrawer:
                                id: stack_non_teaching_borro_ret
                                touch_accept_width: dp(20)
                                anim_type: 'reveal_from_below'
                                side_panel_opacity :0
                                
                        Screen:
                            name:'backup'
                            ScrollView:   
                                size_hint: 1,1
                                bar_width: 15
                                scroll_type: ['bars']
                                bar_color: 0, 52/255, 102/255, 1
                                bar_inactive_color:[0,0,0,0.1]

                                GridLayout:
                                    id: backup_grd
                                    cols:1
                                    size_hint: 1,None
                                    size: 1, self.minimum_height
                                    padding: self.parent.width*1/4,20,self.parent.width*1/4,20
                                    spacing: 20

                        Screen:
                            name:'notifications'
                            ScreenManager:
                                id: sm_noti
                                
                                Screen:
                                    name:'student'
                                    ScrollView:
                                        size_hint: 1,1
                                        bar_width: 15
                                        scroll_type: ['bars']
                                        bar_color: 0, 52/255, 102/255, 1
                                        bar_inactive_color:[0,0,0,0.1]

                                        GridLayout:
                                            id: noti_grid_std
                                            cols:1
                                            size_hint: 1,None
                                            size: 1, self.minimum_height
                                            padding: self.parent.width*1/4,20,self.parent.width*1/4,20
                                            spacing: 20

                                Screen:
                                    name:'teacher'
                                    ScrollView:
                                        size_hint: 1,1
                                        bar_width: 15
                                        scroll_type: ['bars']
                                        bar_color: 0, 52/255, 102/255, 1
                                        bar_inactive_color:[0,0,0,0.1]

                                        GridLayout:
                                            id: noti_grid_teach
                                            cols:1
                                            size_hint: 1,None
                                            size: 1, self.minimum_height
                                            padding: self.parent.width*1/4,20,self.parent.width*1/4,20
                                            spacing: 20

                                Screen:
                                    name:'non'
                                    ScrollView:
                                        size_hint: 1,1
                                        bar_width: 15
                                        scroll_type: ['bars']
                                        bar_color: 0, 52/255, 102/255, 1
                                        bar_inactive_color:[0,0,0,0.1]

                                        GridLayout:
                                            id: noti_grid_non
                                            cols:1
                                            size_hint: 1,None
                                            size: 1, self.minimum_height
                                            padding: self.parent.width*1/4,20,self.parent.width*1/4,20
                                            spacing: 20
                                            
                                            

                        Screen:
                            name:'barcode'
                            BoxLayout:
                                padding: 20, 20, 20, 20
                                spacing: 20

                                ScrollView:
                                    size_hint_x: .3
                                    BoxLayout:
                                        orientation: 'vertical'
                                        size_hint_y: None
                                        height: self.minimum_height
                                        padding: dp(4),dp(4),dp(8),dp(4)
                                        spacing: 20
                                        
                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(220)
                                            BoxLayout:
                                                orientation: 'vertical'
                                                
                                                MDLabel:
                                                    text: 'Generate barcode for book accession number.'
                                                    size_hint_x: 1
                                                    color: 0, 52/255, 102/255, 1
                                                GridLayout:
                                                    cols:2
                                                    padding: 0,0,20,0
                                                    spacing: 8
                                                    MDLabel:
                                                        text: 'from :'
                                                        size_hint_x: None
                                                        width: 50
                                                    Input:
                                                        id: bar_from
                                                        input_filter:'int'
                                                        size_hint_y: None
                                                        height: 50
                                                        
                                                    MDLabel:
                                                        text: 'to :'
                                                        size_hint_x: None
                                                        width: 50
                                                    Input:
                                                        id: bar_to
                                                        input_filter:'int'
                                                        size_hint_y: None
                                                        height: 50
                                                        
                                                MDSeparator:
                                                    size_hint: .6, None
                                                    size: 1,1
                                                    pos_hint: {'center_x':.5}
                                                    
                                                BoxLayout:
                                                    size_hint_y: None
                                                    size: 1,50
                                                    MDFlatButtonc:
                                                        text:'Generate'
                                                        size_hint_x:.3
                                                        on_press: root.generate_barcode(bar_from.text, bar_to.text)
                                                    MDFlatButtonc:
                                                        text:'Print'
                                                        size_hint_x:.3
                                                        on_press: root.print_file()
                                                    MDFlatButtonc:
                                                        text:'preview'
                                                        size_hint_x:.3
                                                        on_press: root.preview_barcode()
                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(450)
                                            orientation: 'vertical'

                                            MDLabel:
                                                text:'Set preference settings'
                                                size_hint_x: 1
                                                color: 0, 52/255, 102/255, 1
                                                
                                            ScrollView:
                                                bar_width: 10
                                                scroll_type:['bars']
                                                bar_color: 0, 52/255, 102/255, 1
                                                bar_inactive_color:[0,0,0,0.4]
                                                
                                                GridLayout:
                                                    
                                                    cols:2
                                                    size_hint: 1, None
                                                    padding: 0,0,50,0
                                                    spacing: 8
                                                    size: 1, self.minimum_height
                                                    
                                                    padding: 0,0,10,0

                                                    MDLabel:
                                                        text:'Page margin x :'
                                                    Input:
                                                        id: margin_x
                                                        
                                                    MDLabel:
                                                        text:'Page margin y :'
                                                    Input:
                                                        id: margin_y
                                                        
                                                    MDLabel:
                                                        text:'Number of column per page :'
                                                    Input:
                                                        id: nocpp
                                                        
                                                    MDLabel:
                                                        text:'Number of rows per page :'
                                                    Input:
                                                        id: norpp
                                                        
                                                    MDLabel:
                                                        text:'Space between barcodes x :'
                                                    Input:
                                                        id: sbbx
                                                        
                                                    MDLabel:
                                                        text:'Space between barcodes y :'
                                                    Input:
                                                        id: sbby
                                                    

                                                    MDFlatButtonc:
                                                        text:'Revert settings'
                                                        size_hint_x: .5
                                                        on_press: root.revert_settings_preview()

                                                    MDFlatButtonc:
                                                        text:'Set settings'
                                                        size_hint_x: .5
                                                        on_press: root.set_settings_preview()
                                            
                                
                                BoxLayout:
                                    size_hint: .7, 1
                                    CardCommon:
                                        
                                        MDFlatButton:
                                            size_hint: None, None
                                            size: 10, self.parent.height
                                            pos_hint:{'left':1}
                                            text:'<'
                                            on_press: root.move_preview_img('p')

                                        FloatLayout:
                                            Image:
                                                id: img_preview
                                                keep_ratio: False
                                                allow_resize: True
                                                pos_hint:{'center_x':.5,'center_y':.5}
                                                size_hint: 1,1
                                                source: 'pics\\no_preview.png'

                                                MDLabel:
                                                    id: lbl_preview
                                                    text:'[b]Page(s): 0/0[/b]'
                                                    markup: True
                                                    size_hint_x: None
                                                    width: 50
                                                    x: self.parent.x+self.parent.width-self.width
                                                    y: self.parent.y+ 20
                                                    color: 0, 52/255, 102/255, 1
                                                    
                                        MDFlatButton:
                                            size_hint: None, None
                                            size: 10, self.parent.height
                                            pos_hint:{'right':1}
                                            text:'>'
                                            on_press: root.move_preview_img('n')
                                          
                                  
                        Screen:
                            name:'analysis'
                            StackLayout:
                                id: stack_analysis
                                orientation:'lr-tb'
                                padding:20,20,20,40
                                spacing:20

                                CardCommon:
                                    size_hint: .45,1
                                    orientation:'vertical'
                                    
                                    BoxLayout:
                                        size_hint: 1,.16
                                        orientation:'vertical'
                                        padding: 5,5,5,5
                                        spacing:5
                                        
                                        MDFlatButtonc:
                                            text:'Estimate a book quantity and how the book is borrowed'
                                            size_hint: 1,None
                                            size:1,60
                                            on_release: root.estimate_book_quantity()
                                       
                                        MDSeparator:
                                            size_hint: 1,None
                                            size: 1,1

                                        TextField:
                                            hint_text: 'Search for a book title'
                                            size_hint_y: None
                                            hint_text_color: 0,0,0,.8
                                            height: 50
                                            on_text_validate: root.search_analysis_books(self.text)

                                        RecycleV:
                                            id: rvanlysis
                                            
                                            
                                            
                                   
                               
                                CardCommon:
                                    size_hint: .55,1
                                    orientation:'vertical'

                                    
                                            
                                    BoxLayout:
                                        size_hint: 1,.5
                                        orientation:'vertical'
                                        padding: 1,5,1,1
                                        spacing:5
                                        
                                        MDLabel:
                                            id: lbl_title0
                                            text:'Title'
                                            halign:'center'
                                            shorten:True
                                            shorten_from:'right'
                                            size_hint: 1,None
                                            size: 1,20
                                            markup:True

                                        ScrollView:
                                            bar_width: 10
                                            scroll_type:['bars']
                                            bar_color: 0, 52/255, 102/255, 1
                                            bar_inactive_color:[0,0,0,0.4]
                                            
                                            
                                            BoxLayout:
                                                size_hint_y: None
                                                height: self.minimum_height
                                                orientation: 'vertical'
                                                
                                                Image:
                                                    id: graph_plot0
                                                    mipmap:True
                                                    allow_stretch:True
                                                    keep_ratio: False
                                                    size_hint: 1,None
                                                    height: 400
                                                    
                                                Image:
                                                    source:'pics/post.png'
                                                    mipmap:True
                                                    allow_stretch: True
                                                    keep_ratio: False
                                                    size_hint: 1, None
                                                    height: 200
                                                    
                                                    ScrollView:
                                                        size_hint: None,None
                                                        size: self.parent.width-100, self.parent.height
                                                        x: self.parent.x + 40
                                                        y: self.parent.y - 70
                                                        
                                                        MDLabel:
                                                            id: lbl_analysis0
                                                            color: 58/255 ,53/255,0,.8
                                                            text_size: self.width-10,None
                                                            size_hint_y: None
                                                            height: self.texture_size[1]
                                                            halign:'left'
                                                            valign:'top'
                                                            font_style:'Caption'
                                                            size_hint: 1,None
                                                            markup: True
                                                            pos: self.parent.pos
                                        MDSeparator:
                                            size_hint: None,None
                                            size: self.parent.width-20,1
                                            pos_hint:{'center_x':.5,'center_y':.5}

                                        MDLabel:
                                            id: lbl_title1
                                            text:'Title'
                                            halign:'center'
                                            shorten:True
                                            shorten_from:'right'
                                            size_hint: 1,None
                                            size: 1,20
                                            markup:True

                                        ScrollView:
                                            bar_width: 10
                                            scroll_type:['bars']
                                            bar_color: 0, 52/255, 102/255, 1
                                            bar_inactive_color:[0,0,0,0.4]
                                            
                                            BoxLayout:
                                                size_hint_y: None
                                                height: self.minimum_height
                                                orientation: 'vertical'
                                                
                                                Image:
                                                    id: graph_plot1
                                                    mipmap:True
                                                    allow_stretch:True
                                                    keep_ratio: False
                                                    size_hint: 1,None
                                                    height: 400
                                                    
                                                Image:
                                                    source:'pics/post.png'
                                                    mipmap:True
                                                    allow_stretch: True
                                                    keep_ratio: False
                                                    size_hint: 1, None
                                                    height: 200
                                                    
                                                    ScrollView:
                                                        size_hint: None,None
                                                        size: self.parent.width-100, self.parent.height
                                                        x: self.parent.x + 40
                                                        y: self.parent.y - 70
                                                        
                                                        MDLabel:
                                                            id: lbl_analysis1
                                                            color: 58/255 ,53/255,0,.8
                                                            text_size: self.width-10,None
                                                            size_hint_y: None
                                                            height: self.texture_size[1]
                                                            halign:'left'
                                                            valign:'top'
                                                            font_style:'Caption'
                                                            size_hint: 1,None
                                                            markup: True
                                                            pos: self.parent.pos
                        Screen:
                            name:'settings'
                            BoxLayout:
                                spacing:20
                                padding: 20,20,20,20
                                BoxLayout:
                                    size_hint: .5,1
                                    orientation:'vertical'
                                    spacing:20
                                    
                                    CardCommon:
                                        size_hint:1 , .5
                                        
                                        ScreenManager:
                                            id: sm_sett

                                            Screen:
                                                name:'switch'
                                                FloatLayout:
                                                    orientation:'vertical'
                                                    
                                                    MDFlatButtonc:
                                                        text:'Change password'
                                                        on_release: sm_sett.current='change'
                                                        pos_hint:{'center_x':.5,'center_y':.6}
                                                        
                                                    MDFlatButtonc:
                                                        text:'Create a new user'
                                                        on_release: sm_sett.current='user'
                                                        pos_hint:{'center_x':.5,'center_y':.4}
                                                        

                                            Screen:
                                                name:'user'
                                                BoxLayout:
                                                    size_hint: 1,1
                                                    orientation:'vertical'
                                                    MDLabel:
                                                        text:'Create a new user account'
                                                        halign:'center'
                                                        size_hint: 1,None
                                                        size: 1,60
                                                    MDSeparator:
                                                        size_hint: None,None
                                                        size: self.parent.width-20, 1
                                                        pos_hint:{'center_x':.5,'center_y':.5}
                                                        
                                                    GridLayout:
                                                        cols: 2
                                                        padding: 10,10,10,0
                                                        spacing: 8
                                                        
                                                        MDLabel:
                                                            text:'User name :'
                                                        TextField:
                                                            id: username
                                                            size_hint_y: None
                                                            height: 50
                                                        MDLabel:
                                                            text:'Password :'
                                                        TextField:
                                                            id: apasswd
                                                            password:True
                                                            size_hint_y: None
                                                            height: 50
                                                        MDLabel:
                                                            text:'Confirm password :'
                                                        TextField:
                                                            id: aconfpasswd
                                                            password:True
                                                            size_hint_y: None
                                                            height: 50
                                                        MDFlatButtonc:
                                                            text:'Back'
                                                            on_release:sm_sett.current='switch'
                                                            size_hint: .1,None
                                                            size: 1,40

                                                        MDFlatButtonc:
                                                            text:'Create'
                                                            size_hint: .1,None
                                                            size: 1,40
                                                            on_release: root.create_new_account(username.text, apasswd.text, aconfpasswd.text)

                                                    
                                            Screen:
                                                name:'change'
                                                BoxLayout:
                                                    orientation:'vertical'
                                                    MDLabel:
                                                        text:'Change password'
                                                        halign:'center'
                                                        size_hint: 1,None
                                                        size: 1,60
                                                    MDSeparator:
                                                        size_hint: None,None
                                                        size: self.parent.width-20, 1
                                                        pos_hint:{'center_x':.5,'center_y':.5}

                                                    GridLayout:
                                                        cols: 2
                                                        padding: 10,10,10,0
                                                        spacing: 8
                                                        MDLabel:
                                                            text:'Current password :'
                                                        TextField:
                                                            id: oldpass
                                                            password:True
                                                            size_hint_y: None
                                                            height: 50
                                                        MDLabel:
                                                            text:'New password :'
                                                        TextField:
                                                            id: newpass
                                                            password:True
                                                            size_hint_y: None
                                                            height: 50
                                                        MDLabel:
                                                            text:'Confirm password :'
                                                        TextField:
                                                            id: confrmpass
                                                            password:True
                                                            size_hint_y: None
                                                            height: 50
                                                        MDFlatButtonc:
                                                            text:'Back'
                                                            on_release:sm_sett.current='switch'
                                                            size_hint:.0,None
                                                            size: .1,40
                                                        MDFlatButtonc:
                                                            text:'Change'
                                                            size_hint: .1,None
                                                            size: 1,40
                                                            on_release: root.change_password(oldpass.text,newpass.text,confrmpass.text)
                                                            
                                                            
                                    CardCommon:
                                        size_hint:1 , .3
                                        orientation: 'vertical'
                                        padding: dp(8),0,0,0

                                        MDLabel:
                                            text: 'Choose Theme'
                                            font_style: 'Subhead'
                                            size_hint_y: None
                                            halign: 'left'
                                            height: dp(30)
                                            
                                        MDSeparator:
                                            size_hint: 1, None
                                            height: dp(1)
                                            
                                        ScrollView:
                                            bar_width: 10
                                            scroll_type:['bars']
                                            bar_color: 0, 52/255, 102/255, 1
                                            bar_inactive_color: [0,0,0,0.4]
                                            
                                            BoxLayout:
                                                size_hint_x: None
                                                width: self.minimum_width
                                                spacing: dp(16)
                                                padding: dp(8),dp(8),dp(8),dp(8)

                                                CustomTgglButton:
                                                    text: 'No theme'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(None)

                                                Image_Theme:
                                                    id: tgle_blur
                                                    source: 'pics\\blur.jpg'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_blur2
                                                    source: 'pics\\blur2.jpg'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_water
                                                    source: 'pics\\water1.zip'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_nature
                                                    source: 'pics\\nature.zip'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_book
                                                    source: 'pics\\book.zip'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_tech
                                                    source: 'pics\\tech.zip'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)

                                                Image_Theme:
                                                    id: tgle_stream
                                                    source: 'pics\\stream.zip'
                                                    size_hint: None, 1
                                                    width: self.parent.height
                                                    group: 'theme'
                                                    on_press: root.set_theme(self)
                                                
                                            

                                BoxLayout:
                                    size_hint: .5,1
                                    orientation:'vertical'
                                    spacing:20

                                    BoxLayout:
                                        orientation: 'vertical'
                                        padding: dp(16),dp(8),dp(16),dp(8)
                                        spacing:dp(8)

                                        CardCommon:
                                            orientation: 'vertical'
                                            size_hint_y: None
                                            height: dp(96)

                                            BoxLayout:
                                                size_hint: 1,None
                                                height: dp(48)
                                                padding: 10,0,0,0
                                                MDLabel:
                                                    text: 'Apply for barcode book issuing pattern'
                                                    size_hint: 1,1
                                                    halign: 'left'

                                            BoxLayout:
                                                size_hint: 1, None
                                                height: dp(48)
                                                padding: 10,0,0,0
                                                
                                                MDLabel:
                                                    text: '[b]Yes[/b]'
                                                    markup: True
                                                    color: 0,0,0,.83
                                                    size_hint_x: None
                                                    width: 30
                                                
                                                CheckBox:
                                                    id: apply_b_i
                                                    size_hint: None, None
                                                    size: dp(48), dp(48)
                                                    group: 'apply_bp'
                                                    active: False
                                                    on_press: self.active=True

                                                MDLabel:
                                                    text: '[b]No[/b]'
                                                    markup: True
                                                    color: 0,0,0,.83
                                                    size_hint_x: None
                                                    width: 30
                                                
                                                CheckBox:
                                                    id: apply_b_i2
                                                    size_hint: None, None
                                                    size: dp(48), dp(48)
                                                    group: 'apply_bp'
                                                    active: True
                                                    on_press: self.active=True

                                        CardCommon:
                                            orientation: 'vertical'
                                            padding: dp(16),dp(16),dp(16),dp(16)
                                            spacing:dp(16)

                                            MDLabel:
                                                text: 'Restrict the no. of books borrowed by students'
                                                size_hint: 1,1
                                                halign: 'left'

                                            BoxLayout:
                                                spacing: dp(8)
                                                TextField:
                                                    id: txt_b_std
                                                    text: '6'
                                                    size_hint: None, None
                                                    font_name: 'fonts\\Montserrat-Light.ttf'
                                                    size: dp(80), dp(30)
                                                    padding_y: 5,0

                                                MDLabel:
                                                    text: 'book(s)'
                                                    size_hint_y: 1
                                                    color: 0,0,0,.83
                                                    halign: 'left'

                                                MDFlatButton:
                                                    text: 'APPLY CHANGES'
                                                    on_release: root.apply_changes('s')
                                                    

                                            MDSeparator:
                                                size_hint: 1, None
                                                height: dp(1)

                                            MDLabel:
                                                text: 'Restrict the no. of books borrowed by Teachers'
                                                size_hint: 1,1
                                                halign: 'left'

                                            BoxLayout:
                                                spacing: dp(8)
                                                TextField:
                                                    id: txt_b_tch
                                                    text: '6'
                                                    size_hint: None, None
                                                    font_name: 'fonts\\Montserrat-Light.ttf'
                                                    size: dp(80), dp(30)
                                                    padding_y: 5,0

                                                MDLabel:
                                                    text: 'book(s)'
                                                    size_hint_y: 1
                                                    color: 0,0,0,.83
                                                    halign: 'left'

                                                MDFlatButton:
                                                    text: 'APPLY CHANGES'
                                                    on_release: root.apply_changes('t')
                                                    

                                            MDSeparator:
                                                size_hint: 1, None
                                                height: dp(1)

                                            MDLabel:
                                                text: 'Restrict the no. of books borrowed by Non teaching stuff'
                                                size_hint: 1,1
                                                halign: 'left'

                                            BoxLayout:
                                                spacing: dp(8)
                                                TextField:
                                                    id: txt_b_nontch
                                                    text: '6'
                                                    size_hint: None, None
                                                    font_name: 'fonts\\Montserrat-Light.ttf'
                                                    size: dp(80), dp(30)
                                                    padding_y: 5,0

                                                MDLabel:
                                                    text: 'book(s)'
                                                    size_hint_y: 1
                                                    color: 0,0,0,.83
                                                    halign: 'left'

                                                MDFlatButton:
                                                    text: 'APPLY CHANGES'
                                                    on_release: root.apply_changes('nt')
                                                    

                                                

                                    MDLabel:
                                        size_hint_y: None
                                        height: dp(15)
                                        text:'Powered by Awwads Cash In Softwares'
                                        pos_hint:{'center_x':.5,'center_y':.5}
                                        color: 0,0,0,.83
                                        
                                        
                        Screen:
                            name:'reports'

                            BoxLayout:
                                spacing: 20
                                padding: 20,20,20,20

                                ScrollView:
                                    size_hint: .3, 1
                                    
                                    BoxLayout:
                                        orientation: 'vertical'
                                        padding: dp(4),dp(4),dp(8),dp(4)
                                        spacing: 20
                                        size_hint: 1, None
                                        height: self.minimum_height

                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(200)
                                            BoxLayout:
                                                orientation: 'vertical'
                                                
                                                MDLabel:
                                                    text: 'Generate reports for'
                                                    color: 0, 52/255, 102/255, 1
                                                    halign: 'center'
                                                    size_hint: 1, .2
                                                ScrollView:
                                                    size_hint: 1, .8
                                                    bar_width: 10
                                                    scroll_type:['bars']
                                                    bar_color: 0, 52/255, 102/255, 1
                                                    bar_inactive_color: [0,0,0,0.4]

                                                    GridLayout:
                                                        cols: 2
                                                        size_hint: None, None
                                                        size: self.minimum_size
                                                        padding: 20,0,0,0
                                                        spacing: 20,0
                                                        
                                                        MDLabel:
                                                            text: 'those who have lost books'
                                                        CheckBox:
                                                            id: chkbx_lost
                                                            group: 'report'
                                                            size_hint: None, None
                                                            size: dp(48), dp(48)
                                                            active: True
                                                            on_press: self.active=True
                                                            
                                                        MDLabel:
                                                            text: 'those who have damaged books'
                                                        CheckBox:
                                                            id: chkbx_damaged
                                                            group: 'report'
                                                            size_hint: None, None
                                                            size: dp(48), dp(48)
                                                            on_press: self.active=True
                                                            
                                                        MDLabel:
                                                            text: 'those suppossed to return books'
                                                        CheckBox:
                                                            id: chkbx_return
                                                            group: 'report'
                                                            size_hint: None, None
                                                            size: dp(48), dp(48)
                                                            on_press: self.active=True
                                            
                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(380)
                                            BoxLayout:
                                                orientation: 'vertical'
                                                size_hint_y: 1

                                                MDLabel:
                                                    text: 'Describe the Headings'
                                                    color: 0, 52/255, 102/255, 1
                                                    halign: 'center'
                                                    size_hint: 1, .2

                                                ScrollView:
                                                    size_hint: 1,.8
                                                    bar_width: 10
                                                    scroll_type:['bars']
                                                    bar_color: 0, 52/255, 102/255, 1
                                                    bar_inactive_color: [0,0,0,0.4]

                                                    GridLayout:
                                                        size_hint: 1, None
                                                        height: self.minimum_height
                                                        cols: 2
                                                        padding: 10,0,20,8
                                                        spacing: 8
                                                        MDLabel:
                                                            text: 'Title :'
                                                            halign: 'left'
                                                            size_hint_x: .48
                                                        TextField:
                                                            id: title_preview
                                                        MDLabel:
                                                            text: 'Sub title :'
                                                            halign: 'left'
                                                            size_hint_x: .48
                                                        TextField:
                                                            hint_text: 'THE LIBRARY DEPARTMENT'
                                                            id: sub_title_preview
                                                        MDLabel:
                                                            text: 'P.O BOX :'
                                                            halign: 'left'
                                                            size_hint_x: .48
                                                        TextField:
                                                            id: box_preview
                                                            
                                                        MDLabel:
                                                            text: 'Telephone no. :'
                                                            halign: 'left'
                                                            size_hint_x: .48
                                                        TextField:
                                                            id: tel_no_preview
                                                        MDLabel:
                                                            text: 'Motto :'
                                                            halign: 'left'
                                                            size_hint_x: .48
                                                        TextField:
                                                            id: motto_preview

                                                        
                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(150)
                                            BoxLayout:
                                                orientation: 'vertical'
                                                size_hint_y: 1

                                                MDLabel:
                                                    text: 'Describe the Report Message'
                                                    color: 0, 52/255, 102/255, 1
                                                    halign: 'center'
                                                    size_hint: 1, .2


                                                TextInput:
                                                    id: describe_mess_preview
                                                    hint_text: 'Type the message here'
                                                    multiline: True
                                                    background_color: 245/255, 245/255, 245/255, .2
                                                    background_normal: ''
                                                    background_active: ''
                                                    cursor_color: 0/255, 109/255, 240/255, 1
                                                        
                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(60)
                                            BoxLayout:
                                                MDFlatButtonc:
                                                    text:'Generate report'
                                                    size_hint: .3,1
                                                    on_press: root.generate_reports( title_preview.text, box_preview.text, tel_no_preview.text, motto_preview.text, sub_title_preview.text, describe_mess_preview.text)
                                                        
                                                MDFlatButtonc:
                                                    text:'Print report'
                                                    size_hint: .3,1
                                                    on_press: root.print_file_reports()
                                                    
                                                MDFlatButtonc:
                                                    text:'Preview report'
                                                    size_hint: .3,1
                                                    on_press: root.preview_reports_0()
                                                    
                                            

                                        CardCommon:
                                            size_hint: 1, None
                                            height: dp(66)
                                            
                                            BoxLayout:
                                                padding: 20,8,20,8
                                                spacing: 20
                                                
                                                MDLabel:
                                                    text: 'Go to page :'
                                                    size_hint_x: .3
                                                    
                                                TextField:
                                                    id: txt_goto
                                                    size_hint_x: .7
                                                    on_text_validate: root.go_to_page(txt_goto.text)
                                                    input_filter: 'int'
                                      
                                BoxLayout:
                                    size_hint: .7, 1
                                    CardCommon:
                                        
                                        MDFlatButton:
                                            size_hint: None, None
                                            size: 10, self.parent.height
                                            pos_hint:{'left':1}
                                            text:'<'
                                            on_press: root.move_preview_img_reports('p')

                                        FloatLayout:
                                            Image:
                                                id: img_preview_reports
                                                keep_ratio: False
                                                mipmap: True
                                                allow_resize: True
                                                pos_hint:{'center_x':.5,'center_y':.5}
                                                size_hint: 1,1
                                                source: 'pics\\no_preview.png'
                                                nocache: True

                                                MDLabel:
                                                    id: lbl_preview_reports
                                                    text:'[b]Page(s): 0/0[/b]'
                                                    markup: True
                                                    size_hint_x: None
                                                    width: 50
                                                    x: self.parent.x+self.parent.width-self.width
                                                    y: self.parent.y+ 20
                                                    color: 0, 52/255, 102/255, 1
                                                    
                                        MDFlatButton:
                                            size_hint: None, None
                                            size: 10, self.parent.height
                                            pos_hint:{'right':1}
                                            text:'>'
                                            on_press: root.move_preview_img_reports('n')

                        Screen:
                            name:'barcode_ret'
                            RecycleVBarcode:
                                id: rv_ret
                                size_hint: 1,1
                                
